# SME0829 Aprendizado de Máquina


por **Cibele Russo**

**ICMC/USP - São Carlos SP**



## Máquinas de suporte vetorial

### Classificação de mensagens em SPAM ou não-SPAM

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import urllib.request
import numpy as np
import pandas as pd

# Leitura dos dados de spam de Rafael Izbicki, de http://www.rizbicki.ufscar.br/ame/ 
url = "http://www.rizbicki.ufscar.br/dados/spam.txt"

# Ler o arquivo .txt em um DataFrame
df = pd.read_csv(url, sep=' ')


df

,make,address,all,tred,our,over,remove,internet,order,mail,...,edu,table,conference,pontVirgula,Parentes,Colchetes,Exclamacao,Cifrao,JogoVelha,spam
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.0,0.0,0.000,0.000,0.0,0.778,0.000,0.000,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.0,0.0,0.000,0.132,0.0,0.372,0.180,0.048,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.06,0.0,0.0,0.010,0.143,0.0,0.276,0.184,0.010,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.0,0.0,0.000,0.137,0.0,0.137,0.000,0.000,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.0,0.0,0.000,0.135,0.0,0.135,0.000,0.000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.31,0.0,0.0,0.000,0.232,0.0,0.000,0.000,0.000,0
4597,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.00,0.0,0.0,0.000,0.000,0.0,0.353,0.000,0.000,0
4598,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,1.20,0.0,0.0,0.102,0.718,0.0,0.000,0.000,0.000,0
4599,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.32,0.0,0.0,0.000,0.057,0.0,0.000,0.000,0.000,0
4600,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.65,0.0,0.0,0.000,0.000,0.0,0.125,0.000,0.000,0

In [23]:
# Separar os atributos (textos dos emails) e os rótulos (SPAM ou não SPAM)
X = df.drop('spam', axis=1)
y = df['spam']

# Dividir o conjunto de dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Treinar o classificador SVM
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)

# Previsões no conjunto de teste
y_pred = svm.predict(X_test)

In [24]:

# Avaliar o desempenho do modelo
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label=1)
recall = recall_score(y_test, y_pred, pos_label=1)
f1 = f1_score(y_test, y_pred, pos_label=1)

# Métricas de desempenho
print('Accuracy:', np.round(accuracy,2))
print('Precision:', np.round(precision,2))
print('Recall:', np.round(recall,2))
print('F1 Score:', np.round(f1,2))

Accuracy: 0.92
Precision: 0.94
Recall: 0.88
F1 Score: 0.91